demo_middleware_auth:
  path:         api/demo/middleware/auth-required
  controller:   LMS\Demo\Controller\DemoApiController::test
  options:
    middleware:
      - auth

demo_middleware:
  path:         api/demo/middleware
  controller:   LMS\Demo\Controller\DemoApiController::test
  options:
    middleware:
      - auth
      - LMS\Routes\Middleware\Api\VerifyAdminBackendSession

demo_throttle:
  path:         api/demo/throttle
  controller:   LMS\Demo\Controller\DemoApiController::test
  options:
    middleware:
      - LMS\Routes\Middleware\Api\Throttle:3,1

demo_middleware_user_owner:
  path:         api/demo/middleware/own
  controller:   LMS\Demo\Controller\DemoApiController::checkOwner
  requirements:
    user:       \d+
    title:      "[^/]+"
  defaults:
    user:
    title:
  options:
    middleware:
      - LMS\Routes\Middleware\Api\VerifyUser:user

demo_middleware_groups:
  path:         api/demo/middleware/in-group
  controller:   LMS\Demo\Controller\DemoApiController::test
  options:
    middleware:
      - auth
      - LMS\Routes\Middleware\Api\VerifyGroup:1,2

demo_middleware_groups_blocked:
  path:         api/demo/middleware/in-group-blocked
  controller:   LMS\Demo\Controller\DemoApiController::test
  options:
    middleware:
      - auth
      - LMS\Routes\Middleware\Api\VerifyGroup:999

demo_action_with_params:
  path:         api/demo/test/with_params
  controller:   LMS\Demo\Controller\DemoApiController::testWithParams
  defaults:
    title:       default-title
    description: default-description

https_only:
  path:         api/demo/https/only
  controller:   LMS\Demo\Controller\DemoApiController::test
  schemes:      https

custom_format:
  path:         api/demo/custom/view
  controller:   LMS\Demo\Controller\DemoApiController::test
  format:       json


demo_index:
  path:         api/demo/photos
  controller:   LMS\Demo\Controller\DemoApiController::index
  methods:      GET

demo_show:
  path:         api/demo/photos/{uid}
  controller:   LMS\Demo\Controller\DemoApiController::show
  methods:      GET
  requirements:
    # The name should be exactly like in controller, as we use Resource Controller, it will be <uid>
    uid:        \d+

demo_store:
  path:         api/demo/photos
  controller:   LMS\Demo\Controller\DemoApiController::store
  methods:      POST
  defaults:
    # data here is required, otherwise we don't know which arguments to expect
    data:

demo_update:
  path:         api/demo/photos/{uid}
  controller:   LMS\Demo\Controller\DemoApiController::update
  methods:      [PUT, PATCH]
  requirements:
    # The name should be exactly like in controller, as we use Resource Controller, it will be <uid>
    uid:      \d+
  defaults:
    # data here is required, otherwise we don't know which arguments to expect
    # use query params here instead of form data
    data:

demo_destroy:
  path:         api/demo/photos/{uid}
  controller:   LMS\Demo\Controller\DemoApiController::destroy
  methods:      DELETE
  requirements:
    # The name should be exactly like in controller, as we use Resource Controller, it will be <uid>
    uid:      \d+
