name: routes
type: typo3
docroot: public
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
  - m.routes
additional_fqdns: []
mariadb_version: "10.5"
use_dns_when_possible: true
composer_version: "2"
web_environment:
  - TYPO3_CONTEXT=Development
timezone: "Europe/Berlin"
