APIVersion: v1.15.1
name: routes
type: typo3
docroot: public
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: true
additional_hostnames:
  - m.routes
additional_fqdns: []
mariadb_version: "10.5"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: "Europe/Berlin"
omit_containers: ["dba", "ddev-ssh-agent"]
hooks:
  post-start:
    - exec: "sudo chmod -R 777 /var/www/html/var"
